name: Build

on: 
  push:
    branches:
      - master


jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: List Available Simulators
      run: xcrun simctl list devices
    - name: Start xcodebuild test
      run: xcodebuild clean build -project TTT.xcodeproj -scheme TTT -destination "platform=iOS Simulator,name=iPhone 13"
