name: Build

on: 
  push:
    branches:
      - master


jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: list destination
      run: xcodebuild clean build -project TTT.xcodeproj -scheme TTT -showdestinations
    - name: Start xcodebuild test
      run: xcodebuild clean build -project TTT.xcodeproj -scheme TTT -destination "platform=iOS Simulator,name=Any iOS Simulator Device"
